# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/floating_point_0/floating_point_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_0 || ORIG_REF_NAME==floating_point_0} -quiet] -quiet
